// 과정이 제공하는 글 30개입니다. 학습자가 만들지 않습니다.
// minute는 올라온 시각을 분으로 적은 값이고, 클수록 나중에 올라온 글입니다.
const POSTS = [
  { id: 1, title: '자취방 6개월 만에 정리한 후기', topic: '자취', minute: 100, likes: 42 },
  { id: 2, title: '3천원으로 한 끼 만들기', topic: '요리', minute: 104, likes: 88 },
  { id: 3, title: '퇴근길에 읽기 좋은 책 다섯 권', topic: '독서', minute: 108, likes: 31 },
  { id: 4, title: '첫 등산에서 배운 것', topic: '운동', minute: 112, likes: 17 },
  { id: 5, title: '원룸 곰팡이 잡는 법', topic: '자취', minute: 116, likes: 64 },
  { id: 6, title: '계란 하나로 만드는 야식', topic: '요리', minute: 120, likes: 55 },
  { id: 7, title: '기록을 남기기 시작한 이유', topic: '독서', minute: 124, likes: 12 },
  { id: 8, title: '집에서 하는 십 분 스트레칭', topic: '운동', minute: 128, likes: 73 },
  { id: 9, title: '월세 계약 전에 확인할 것', topic: '자취', minute: 132, likes: 96 },
  { id: 10, title: '밥솥 하나로 버티는 일주일', topic: '요리', minute: 136, likes: 23 },
  { id: 11, title: '다 못 읽은 책을 대하는 법', topic: '독서', minute: 140, likes: 8 },
  { id: 12, title: '달리기를 오래 하는 사람들의 공통점', topic: '운동', minute: 144, likes: 47 },
  { id: 13, title: '작은 냉장고 정리하는 순서', topic: '자취', minute: 148, likes: 35 },
  { id: 14, title: '자취 3년 차의 양념 목록', topic: '요리', minute: 152, likes: 61 },
  { id: 15, title: '한 달에 두 권만 읽기로 했다', topic: '독서', minute: 156, likes: 19 },
  { id: 16, title: '헬스장을 끊고 알게 된 것', topic: '운동', minute: 160, likes: 28 },
  { id: 17, title: '겨울 난방비를 반으로 줄인 방법', topic: '자취', minute: 164, likes: 105 },
  { id: 18, title: '설거지가 적게 나오는 요리', topic: '요리', minute: 168, likes: 44 },
  { id: 19, title: '책을 사기 전에 하는 일', topic: '독서', minute: 172, likes: 15 },
  { id: 20, title: '계단 오르기가 만만치 않은 이유', topic: '운동', minute: 176, likes: 22 },
  { id: 21, title: '이사할 때 버려서 후회한 것', topic: '자취', minute: 180, likes: 58 },
  { id: 22, title: '냉동실을 잘 쓰는 사람의 습관', topic: '요리', minute: 184, likes: 39 },
  { id: 23, title: '읽은 책을 기억하는 방법', topic: '독서', minute: 188, likes: 26 },
  { id: 24, title: '무릎이 아플 때 멈춰야 하는 신호', topic: '운동', minute: 192, likes: 51 },
  { id: 25, title: '혼자 살면서 생긴 규칙', topic: '자취', minute: 196, likes: 33 },
  { id: 26, title: '장을 일주일에 한 번만 보기', topic: '요리', minute: 200, likes: 67 },
  { id: 27, title: '전자책과 종이책을 나눠 쓰는 기준', topic: '독서', minute: 204, likes: 14 },
  { id: 28, title: '운동을 아침으로 옮긴 뒤', topic: '운동', minute: 208, likes: 40 },
  { id: 29, title: '집에서 소리 덜 나게 사는 법', topic: '자취', minute: 212, likes: 29 },
  { id: 30, title: '남은 재료로 만드는 볶음밥', topic: '요리', minute: 216, likes: 76 },
];
